---
# Per environment values which override defaults in hmpps-prisoner-location/values.yaml

generic-service:
  replicaCount: 2

  scheduledDowntime:
    enabled: true
    startup: '15 6 * * 1-5' # Start at 6.15am UTC Monday-Friday
    shutdown: '24 21 * * 1-5' # Stop at 9.24pm UTC Monday-Friday

  ingress:
    host: prisoner-location-dev.prison.service.justice.gov.uk
    className: modsec-non-prod

  env:
    INGRESS_URL: "https://prisoner-location-dev.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    PRISONER_LOCATION_API_URL: "https://prisoner-location-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: syscon-nonprod

  elastiCacheAlertsClusterIds:
    cp-68c3db92adc3f165-001: "HMPPS Prisoner Location ElastiCache Cluster Node 1"
    cp-68c3db92adc3f165-002: "HMPPS Prisoner Location ElastiCache Cluster Node 2"
